apiVersion: v1
data:
  name: Zmlyc3QtYXBw
  project: ZGVmYXVsdA==
  type: aGVsbQ==
  url: aHR0cHM6Ly9wbHVoaW4uZ2l0aHViLmlvL2hlbG0tMjktMjQv
kind: Secret
metadata:
  name: repo-1115609827
  namespace: argocd
type: Opaque
